version: "3.7"

services:
  database:
    image: postgres
    container_name: pg_database
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pg_docker
    volumes:
      - pgdata:/data/postgres
  
  app:
    build: .
    container_name: pg_app
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local